"""
Script de template para Alembic
"""
"""Add WhatsApp persistence models

Revision ID: 2932e798ff1e
Revises: 0002
Create Date: 2025-10-10 17:21:31.307585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2932e798ff1e'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
